### ISSUE TITLE
Sample::has_cite_seq_data value is wrong for SCPCP000008/SCPCS000368

### ISSUE THREAD

**Issue by arkid15r** [AlexsLemonade/scpca-portal#499]
### Context

While processing AnnData `SCPCP000008` failed with the following error:

```
Importing 'Project SCPCP000008' data
Traceback (most recent call last):
  File "/home/user/manage.py", line 30, in <module>
    main()
  File "/home/user/manage.py", line 26, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/user/scpca_portal/management/commands/load_data.py", line 80, in handle
    load_data_from_s3(
  File "/home/user/scpca_portal/management/commands/load_data.py", line 218, in load_data_from_s3
    computed_files = project.load_data(scpca_sample_ids=scpca_sample_ids)
  File "/home/user/scpca_portal/models/project.py", line 970, in load_data
    ) = ComputedFile.get_sample_single_cell_file(
  File "/home/user/scpca_portal/models/computed_file.py", line 313, in get_sample_single_cell_file
    zip_file.write(file_path, file_name)
  File "/usr/local/lib/python3.10/zipfile.py", line 1741, in write
    zinfo = ZipInfo.from_file(filename, arcname,
  File "/usr/local/lib/python3.10/zipfile.py", line 504, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/data/input/SCPCP000008/SCPCS000368/SCPCL000639_filtered_adt.hdf5'
```

### Problem or idea

The flag is getting wrong value which leads to absent AnnData files processing attempt and the entire project processing failure.

### Solution or next step

Set the value correctly to avoid the issue.

**Comment by davidsmejia** [comment]
Closed with #500
