### ISSUE TITLE
Data processing clean_up_input_data TypeError

### ISSUE THREAD

**Issue by arkid15r** [AlexsLemonade/scpca-portal#510]
### Context

A new error was introduced withing update of the data loading script

### Problem or idea
```

Created 23 samples for 'Project SCPCP000001'
Cleaning up 'Project SCPCP000001' input data
Traceback (most recent call last):
  File "/home/user/manage.py", line 30, in <module>
    main()
  File "/home/user/manage.py", line 26, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/user/scpca_portal/management/commands/load_data.py", line 132, in handle
    self.load_data(**kwargs)
  File "/home/user/scpca_portal/management/commands/load_data.py", line 233, in load_data
    self.clean_up_input_data()
TypeError: Command.clean_up_input_data() missing 1 required positional argument: 'self'
```

### Solution or next step

Fix the clean up method definition.

**Comment by arkid15r** [comment]
Resolved by https://github.com/AlexsLemonade/scpca-portal/pull/511
